title: PCjs Machines
domain: pcjs.dev
description: Welcome to PCjs, home of the original IBM PC emulator for web browsers.
author: Jeff Parsons
logo: /assets/img/logo-home.png
data_dir: configs
google_analytics: UA-155982505-1
left_brace: "{"
right_brace: "}"
encoding: UTF-8

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - README.md
  - "**/archive"
  - "**/private"
  - /package*.json
  - /.history
  - /modules
  - /node_modules
  - /software/pcx86/sys/dos/microsoft/2.11

github:
  owner_name: "jeffpar"
  owner_url: https://github.com/jeffpar
  repository_url: https://github.com/jeffpar/pcjs
  master: https://github.com/jeffpar/pcjs/tree/master

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

plugins:
  - jekyll-feed
  - jekyll-redirect-from

software:
  diskettes:
    server: https://diskettes.pcjs.org
  gamedisks:
    server: https://gamedisks.pcjs.org
  harddisks:
    server: https://harddisks.pcjs.org
