title: PCjs Machines
domain: pcjs.org
tagline: Home of the original IBM PC emulator for browsers.
description: >
  The PCjs Project offers a variety of machine emulations written in JavaScript, including PCx86 for x86-based
  machines (through the 80386), C1Pjs for the 6502-based Ohio Scientific Challenger 1P, PCx80 for 8080-based
  machines like Space Invaders and the DEC VT100 Terminal, PDPjs with support for PDP-10 and PDP-11 machines, and
  emulators of classic programmable calculators, like the TI-57.  PCjs also maintains an archive of selected historical
  software, documentation, and reference materials.
author: Jeff Parsons
logo: /assets/img/logo-home.png
data_dir: configs
left_brace: "{"
right_brace: "}"
encoding: UTF-8

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - README.md
  - TODO.md
  - "*.log"
  - tmp
  - "**/archive"
  - "**/private"
  - /package*.json
  - /.history
  - /modules
  - /node_modules
  - /software/pcx86/sys/dos/microsoft/2.11

github:
  owner_name: "jeffpar"
  owner_url: https://github.com/jeffpar
  repository_url: https://github.com/jeffpar/pcjs.org
  pages: https://github.com/jeffpar/pcjs.org/tree/master

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
#   disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache

software:
  diskettes:
    server: https://diskettes.pcjs.org
  gamedisks:
    server: https://gamedisks.pcjs.org
  harddisks:
    server: https://harddisks.pcjs.org

archive:
  ms:
    server: https://msarchive.pcjs.org
  kb:
    server: https://jeffpar.github.io/kbarchive/
